// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizHub.Models;

namespace QuizHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QuizHub.Models.Quiz_category", b =>
                {
                    b.Property<int>("qc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("qc_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("qc_Id");

                    b.ToTable("quiz_Categories");
                });

            modelBuilder.Entity("QuizHub.Models.Quiz_question", b =>
                {
                    b.Property<int>("qq_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("qc_Id")
                        .HasColumnType("int");

                    b.Property<string>("qq_ans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qq_opta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qq_optb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qq_optc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qq_optd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("quiz_catqc_Id")
                        .HasColumnType("int");

                    b.HasKey("qq_id");

                    b.HasIndex("quiz_catqc_Id");

                    b.ToTable("quiz_Questions");
                });

            modelBuilder.Entity("QuizHub.Models.User", b =>
                {
                    b.Property<int>("u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("u_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("QuizHub.Models.User_progress", b =>
                {
                    b.Property<int>("up_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("rans")
                        .HasColumnType("int");

                    b.Property<int>("u_id")
                        .HasColumnType("int");

                    b.Property<int?>("useru_id")
                        .HasColumnType("int");

                    b.Property<int>("wans")
                        .HasColumnType("int");

                    b.HasKey("up_id");

                    b.HasIndex("useru_id");

                    b.ToTable("user_Progresses");
                });

            modelBuilder.Entity("QuizHub.Models.Quiz_question", b =>
                {
                    b.HasOne("QuizHub.Models.Quiz_category", "quiz_cat")
                        .WithMany("quiz_que")
                        .HasForeignKey("quiz_catqc_Id");

                    b.Navigation("quiz_cat");
                });

            modelBuilder.Entity("QuizHub.Models.User_progress", b =>
                {
                    b.HasOne("QuizHub.Models.User", "user")
                        .WithMany("user_Progresses")
                        .HasForeignKey("useru_id");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QuizHub.Models.Quiz_category", b =>
                {
                    b.Navigation("quiz_que");
                });

            modelBuilder.Entity("QuizHub.Models.User", b =>
                {
                    b.Navigation("user_Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
